[tox]
envlist =
    python{3.10,3.11,3.12}-django{5.2}-wagtail{7.0,7.3,7.4},
    python{3.13}-django{5.2}-wagtail{7.0},
    python{3.13}-django{5.2,6.0}-wagtail{7.3,7.4},
    python{3.14}-django{5.2,6.0}-wagtail{7.3,7.4},

[gh-actions]
python =
    3.10: python3.10
    3.11: python3.11
    3.12: python3.12
    3.13: python3.13
    3.14: python3.14

[testenv]
commands = coverage run --parallel -m pytest {posargs} -vvv

basepython =
    python3.10: python3.10
    python3.11: python3.11
    python3.12: python3.12
    python3.13: python3.13
    python3.14: python3.14

deps =
    django5.2: Django>=5.2,<6.0
    django6.0: Django>=6.0,<6.1
    wagtail7.0: wagtail>=7.0,<7.1
    wagtail7.3: wagtail>=7.3,<7.4
    wagtail7.4: wagtail>=7.4,<7.5

extras = test

[testenv:coverage-report]
deps = coverage
skip_install = true
commands =
    coverage combine
    coverage report
